#server config
server:
  port: 8001

#Spring Data jpa config
spring:
  jpa:
    #指定是否在Spring容器启动时创建表,默认为false
    generate-ddl: true
    #指定是否在控制台显示SQL语句,默认为false
    show-sql: true
    #指定应用重启时不更新表
    hibernate:
      ddl-auto: none


  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useInformationSchema=true&useSSL=true
    username: root
    password: root

#log config
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.abc.msc: debug








