#server config
server:
  port: 9002

#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver7001.com:7001/eureka,http://eurekaserver7002.com:7002/eureka,http://eurekaserver7003.com:7003/eureka
  instance:
    instance-id: 02-consumer-9002
spring:
  application:
    name: eurekaconsumer #微服务对外暴露的名称


