#server config
server:
  port: 9002

#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #指定eureka注册中心地址
  instance:
    instance-id: 02-consumer-9002
spring:
  application:
    name: eurekaconsumer #微服务对外暴露的名称


